version: 2.1
# Use a package of configuration called an orb.
orbs:
  welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
commands:
  # Exercise: Reusable Job Code
  print_pipeline_id:
    parameters:
      id: 
        type: string
    steps:
      - run: echo << parameters.id >>

  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable 
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID 
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

# Define the jobs we want to run for this project
jobs:
  print_greetings:
    docker:
      - image: circleci/node:13.8.0
    environment:
      _env_name: 123
    steps:
      - print_pipeline_id:
          id: << pipeline.id >>
      - print_pipeline_id:
          id: << "hello print_pipeline_id" >>
      - run: echo HELLO
      - run: echo WORLD
      - run: echo $_env_name

  # Exercise: Sharing Files (Job names may have changed)
  upload_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "THIS IS A SAMPLE TEXT" > ~/output.txt  
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt  

  download_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt 

  # # Exercise: Config and Deployment
  # configure_infrastructure: 
  #   docker:
  #     - image: 
  #   steps:
  #     - checkout
  #     - add_ssh_keys:
  #         fingerprints: ["61:22:79:6b:8b:79:4e:87:e1:ae:71:57:02:9d:1a:f2"] 
  #     - run:
  #         name: Install Ansible
  #         command: |
  #           # Install Ansible
  #     - run:
  #         name: Run Playbook and Configure server
  #         command: |
  #           # Your command
  # create_infrastructure: 
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1
      # Fail the job intentionally to simulate an error.
      # Uncomment the line below if you want to fail the current step
      # - run: return 1
      # - destroy_environment
# Sequential workflow
workflows:
  # Name the workflow
  my_workflow:
    jobs:
      - welcome/run
      - print_greetings
      - upload_file
      - download_file:
          requires:
            - upload_file