version: '3.9'
services:
  web:
    image: bentoml_service:zjv7jgawmopqhi5a
    container_name: bentoml_service
    environment:
      - BENTOML_CONFIG=/home/bentoml/configuration.yml
    volumes:
      - ./configuration.yml:/home/bentoml/configuration.yml
    command: serve
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web


