data_path: "./phase-1/prob-2/raw_train.parquet"
parameters:
  seed: 108
  n_cv_splits: 5
  test_size: 0.2
  
# Parameters for XGBoost: https://xgboost.readthedocs.io/en/stable/parameter.html
params_xgb:
  grow_policy: "lossguide"
  max_leaves: 6
  min_child_weight: 2
  learning_rate: 0.05
  subsample: 0.5
  colsample_bytree: 0.6
  max_bin: 255
  gamma: 1.0
  reg_alpha: 1.0
  reg_lambda: 5.0
  tree_method: "hist"
  objective: "binary:logistic"
  eval_metric: "auc"

params_lgbm_backup:
  random_state: 42
  objective: "binary"
  num_leaves: 7
  learning_rate: 0.1
  subsample: 0.5
  colsample_bytree: 0.5
  reg_alpha: 5
  reg_lambda: 5
  max_bin: 255
  min_child_samples: 20
  min_child_weight: 0.1
  n_estimators: 1000

params_lgbm:
  random_state: 42
  objective: "binary"
  num_leaves: 7
  learning_rate: 0.1
  subsample: 0.5
  colsample_bytree: 0.5
  reg_alpha: 5
  reg_lambda: 5
  max_bin: 255
  min_child_samples: 20
  min_child_weight: 0.1
  n_estimators: 1000