data_path: "./phase-1/prob-1/raw_train.parquet"
parameters:
  seed: 108
  n_cv_splits: 5
  test_size: 0.2
  
# Parameters for XGBoost: https://xgboost.readthedocs.io/en/stable/parameter.html
params_xgb:
  grow_policy: "lossguide"
  max_leaves: 6
  min_child_weight: 2
  learning_rate: 0.05
  subsample: 0.5
  colsample_bytree: 0.6
  max_bin: 255
  gamma: 1.0
  reg_alpha: 1.0
  reg_lambda: 5.0
  tree_method: "hist"
  objective: "binary:logistic"
  eval_metric: "auc"

params_lgbm:
  random_state: 42
  objective: "binary"
  is_unbalance: true
  n_estimators: 1000
  learning_rate: 0.12082860547692932
  num_leaves: 2720
  max_depth: 7
  min_data_in_leaf: 200
  lambda_l1: 0
  lambda_l2: 45
  min_gain_to_split: 5.9603828488935235
  bagging_fraction: 0.4
  bagging_freq: 1
  feature_fraction: 0.9

# Trial 101 finished with value: 0.018597445338409086 and parameters: {'n_estimators': 2000, 'learning_rate': 0.16995658635435387, 'num_leaves': 1700, 'max_depth': 10, 'min_data_in_leaf': 300, 'lambda_l1': 5, 'lambda_l2': 45, 'min_gain_to_split': 0.014979213744235421, 'bagging_fraction': 0.7, 'bagging_freq': 1, 'feature_fraction': 0.9, 'device_type': True}